esphome:
  name: air_purifier 
  platform: ESP8266
  board: d1_mini
  includes:
    - sharp_sensor.h
    
wifi:
  ssid: "######"
  password: "#####"


  ap:
    ssid: "#####"
    password: "######"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# custom sensor 
sensor:
- platform: custom
  lambda: |-
    auto dust_Sensor = new My_dust_Sensor(); 
    App.register_component(dust_Sensor);
    return {dust_Sensor};
    
  sensors:
    name: "Dust sensor"
    accuracy_decimals: 2
    unit_of_measurement: "%"
    # "unit_of_measurement" must be set, otherways HA will show history like a "binary sensor", not line graph



